### ISSUE TITLE
Ascom cannot import bundled assets on legacy circumstances

### ISSUE THREAD

**Issue by anikris1** [AlaskaAirlines/auro-dropdown#198] opened 2023-06-16 16:32 UTC
### Please verify the version of auro-dropdown you have installed

v2.9.9

### Please describe the bug

we're looking to import the auro-datepicker, auro-dropdown into the homelet on the Ascom homepage. 

### Reproducing the error

None

**Comment by Patrick-Daly-AA** [comment] 2024-08-14 20:06
deleting as this is a duplicate of #199

**Closed as not planned by Patrick-Daly-AA** 2024-08-14 20:06 UTC
Labels: auro-dropdown, not-reviewed, Type: Bug
