### ISSUE TITLE
POC - auro-popover: Native support

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-dropdown#239] opened 2024-05-09 21:15 UTC
### Is your feature request related to a problem? Please describe.

We would like to incorporate the new native HTML version of popover.  We need to first identify the scope of this work.  What components will end up changes as a result of this. 

We have had a number of issues where the popover doesn't appear where it should and our hypothesis is that leveraging the native popover will be more reliable and allow us to get rid of popover.js

### Describe the solution you'd like

This component is either retired and replaced with native support or this component is updated to utilize native html support.  

### Additional context

This component is often used in auro-dialog for form components and it is in those state where we see the majority of issues.

### Exit criteria

1. a POC version of Auro-Popover has been created that uses native Popover to validate that it will fit our needs
2. Nees to show using a popover in full screen desktop, mobile, and in a bib.
3. The POC is not complete until we also outline what the keyboard accessibility experience is out of the box.
4. Anything that native popover doesn't do, but popperJS does do (that we use) is documented and brought to the team for discussion about how we want to approach that issue.
5. Determine how Native popover will impact the mobile experience and if it will be suitable for mobile

**Comment by jordanjones243** [comment] 2024-09-13 16:14
The outcome of this POC was that it is not what we want to use to replace PopperJS because of the lack of positioning API needed to achieve how we want the component to behave. I am not closing this out yet, but moving back to investigating, as there was some discussion about using the modal dialog features provided in Native Popover in order to achieve the new dropdown mobile look.

**Comment by Patrick-Daly-AA** [comment] 2024-09-25 21:27
Native Popover will not meet our needs.  We are investigating Floating UI instead.

**Closed as completed by Patrick-Daly-AA** 2024-09-25 21:27 UTC
Labels: auro-dropdown

**Comment by jason-capsule42** [comment] 2024-10-03 06:47
Duplicate of #218
